### ISSUE TITLE
Unable to parse the frame rate string

### ISSUE THREAD

**Issue by hmishinev** [shaka-project/shaka-packager#1124]
## System info
**Operating System**: macOS Monterey
**Shaka Packager Version**: v2.6.1

## Issue and steps to reproduce the problem

**Packager Command**:

1. Use any MOV video captured with iPhone
2. Try to process that video

What is the expected result?

The video is processed successfuly

What happens instead?

The following error is thrown:

```
+ ffprobe /Users/hmishinev/Projects/Reedsy/reedsy-videos/tmp/raw/video_bundle_58104c69-bbe2-45b7-be92-364d248ba84e/video -select_streams v:0 -show_entries stream=index -of compact=p=0:nk=1
+ ffprobe /Users/hmishinev/Projects/Reedsy/reedsy-videos/tmp/raw/video_bundle_58104c69-bbe2-45b7-be92-364d248ba84e/video -select_streams v:0 -show_entries stream=field_order -of compact=p=0:nk=1
+ ffprobe /Users/hmishinev/Projects/Reedsy/reedsy-videos/tmp/raw/video_bundle_58104c69-bbe2-45b7-be92-364d248ba84e/video -select_streams v:0 -show_entries stream=avg_frame_rate -of compact=p=0:nk=1
Traceback (most recent call last):
  File "/opt/homebrew/bin/shaka-streamer", line 125, in <module>
    sys.exit(main())
  File "/opt/homebrew/bin/shaka-streamer", line 104, in main
    with controller.start(args.output, input_config_dict, pipeline_config_dict,
  File "/opt/homebrew/lib/python3.10/site-packages/streamer/controller_node.py", line 179, in start
    self._input_config = InputConfig(input_config_dict)
  File "/opt/homebrew/lib/python3.10/site-packages/streamer/input_configuration.py", line 405, in __init__
    super().__init__(dictionary)
  File "/opt/homebrew/lib/python3.10/site-packages/streamer/configuration.py", line 325, in __init__
    value = self._check_and_convert_type(field, key, value)
  File "/opt/homebrew/lib/python3.10/site-packages/streamer/configuration.py", line 381, in _check_and_convert_type
    return [self._check_and_convert_type(subfield, key, v) for v in value]
  File "/opt/homebrew/lib/python3.10/site-packages/streamer/configuration.py", line 381, in <listcomp>
    return [self._check_and_convert_type(subfield, key, v) for v in value]
  File "/opt/homebrew/lib/python3.10/site-packages/streamer/configuration.py", line 368, in _check_and_convert_type
    sub_object = field.type(value)
  File "/opt/homebrew/lib/python3.10/site-packages/streamer/input_configuration.py", line 244, in __init__
    self.frame_rate = autodetect.get_frame_rate(self)
  File "/opt/homebrew/lib/python3.10/site-packages/streamer/autodetect.py", line 125, in get_frame_rate
    frame_rate = float(fraction[0]) / float(fraction[1])
ValueError: could not convert string to float: '1091|'
```

https://github.com/shaka-project/shaka-streamer/blob/main/streamer/autodetect.py#L124

A test video file is available here: https://drive.google.com/file/d/1RS90AgRXLus1o_8JeD_pKFlAUKkQJCp6/view?usp=sharing

**Comment by joeyparrish** [comment]
I believe this belongs in the shaka-streamer repo.  I'll move the issue.  Thanks!
