### ISSUE TITLE
Segmentation fault on shaka::Period::GetAdaptationSets()

### ISSUE THREAD

**Issue by murillo128** [shaka-project/shaka-packager#1172]
## System info
Ubunto 22.04
Shaka Packager Version: d5ca6e84e6ccd543dc9a79ccc8d07b702010f491

## Issue and steps to reproduce the problem

This happened on a production server, not sure what have been the exact conditions for reproducing the problem.

This is the back trace of the segmentation fault:

```
Thread 1 (Thread 0x7fb207d7f7c0 (LWP 1825)):
#0  0x00007fb1ee344894 in shaka::Period::GetAdaptationSets[abi:cxx11]() const () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#1  0x00007fb1ee1d4e36 in shaka::MpdBuilder::GetEarliestTimestamp(double*) () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#2  0x00007fb1ee1d60ad in shaka::MpdBuilder::AddDynamicMpdInfo(shaka::xml::XmlNode*) () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#3  0x00007fb1ee1d7145 in shaka::MpdBuilder::GenerateMpd() () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#4  0x00007fb1ee1d7466 in shaka::MpdBuilder::ToString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#5  0x00007fb1ee1d455e in shaka::WriteMpdToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, shaka::MpdBuilder*) () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
#6  0x00007fb1ee1cb00d in shaka::SimpleMpdNotifier::Flush() () from /opt/millicast/bin/medooze/node_modules/medooze-shaka-packager/build/Release/medooze-shaka-packager.node
```

https://github.com/shaka-project/shaka-packager/blob/576889eecc1b7585c8f8d2f294f8d43590cced1e/packager/mpd/base/mpd_builder.cc#L351

Somehow the `periods`  are empty, causing the crash. There is a DCHECK in place, but that doesn't prevent the code from crashing.

**Comment by joeyparrish** [comment]
It would be best to figure out why periods are empty.  This may be an issue with the calls you make into the library.  Are you using Packager as a library or via the command-line frontend?
