### ISSUE TITLE
pssh-box.py in Docker container -> ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by emarsden** [shaka-project/shaka-packager#1436]
## System info
**Operating System**: Debian 13
**Shaka Packager Version**: HEAD

## Issue and steps to reproduce the problem

Running the pssh-box.py utility from the latest version of the Docker image (and for all version tags > 3.0) leads to an error

```
% podman run --rm docker.io/google/shaka-packager:latest pssh-box.py --from-base64 "AAAAnnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAH4IARIQNeHmMAKWzF5NJTqHEIQDChoMaW5rYWVudHdvcmtzIlpuZWV0LXBnLWRyLXNvdW1lbi1tYW5uYS0xMDgwLWxpdmUtdmVyc2lvbi02LWdlbmVyYWwtcGh5aXNvbG9neS1uZXctcnItNi0wLWhpbmRpOTgxMTQtOTAxMjk="
Traceback (most recent call last):
  File "/usr/bin/pssh-box.py", line 46, in <module>
    import widevine_pssh_data_pb2
  File "/usr/bin/pssh-box-protos/widevine_pssh_data_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```

With version 2.5.1 this worked as expected: 

```
% podman run --rm docker.io/google/shaka-packager:v2.5.1 pssh-box.py --from-base64 "AAAAnnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAH4IARIQNeHmMAKWzF5NJTqHEIQDChoMaW5rYWVudHdvcmtzIlpuZWV0LXBnLWRyLXNvdW1lbi1tYW5uYS0xMDgwLWxpdmUtdmVyc2lvbi02LWdlbmVyYWwtcGh5aXNvbG9neS1uZXctcnItNi0wLWhpbmRpOTgxMTQtOTAxMjk="
Trying to pull docker.io/google/shaka-packager:v2.5.1...
PSSH Box v0
  System ID: Widevine edef8ba9-79d6-4ace-a3c8-27dcd51d21ed
  PSSH Data (size: 126):
    Widevine Data:
      Key IDs (1):
        35e1e630-0296-cc5e-4d25-3a871084030a
      Provider: inkaentworks
      Content ID: 6E6565742D70672D64722D736F756D656E2D6D616E6E612D313038302D6C6976652D76657273696F6E2D362D67656E6572616C2D70687969736F6C6F67792D6E65772D72722D362D302D68696E646939383131342D3930313239
```

**Comment by joeyparrish** [comment]
Confirmed via docker (replaced "podman" with "docker" in above commands.
